### ISSUE TITLE
Is it possible to expose an internal container port on a different port?

### ISSUE THREAD

**Issue by josegonzalez** [gdm85/docker-fw#7]
I'll admit that my knowledge of how iptables works is a bit low, but essentially what I'd like to do is accept connections on a new port for a docker container that was not started with either `-P` or `-p`. Is it possible to use docker-fw to do that, and if so, how?

**Comment by xinity** [comment]
Nop this isn't possible I think. Without -p or -P your container network port will only be accessible within your "docker network"

**Comment by josegonzalez** [comment]
Alright cool, thanks for the update :)

**Comment by gdm85** [comment]
Well, it depends from the option `--icc=false`. If it would be set to true, I think it would be possible.

However the suggested default is `icc=false`.

I remember seeing an issue/feature request about this on Docker issue tracker, you might follow up from there, maybe it was added as an option or a workaround exists to change the published ports of a container.

**Comment by josegonzalez** [comment]
Yeah I've been reading their channel. Kind of annoying that you can't restart a container and publish the port on start. I've tested https://github.com/Memset/tcp_fallback and it seems to do what I want to do, so I might go with that as a solution, or perhaps run it in a container that is linked against a private container.

**Comment by gdm85** [comment]
Wow, that looks like a massive hack :)

The private container approach it's called [ambassador pattern](https://docs.docker.com/articles/ambassador_pattern_linking/); actually I think in theory it would be possible to do what you mentioned in OP via docker-fw (my README even mentions it) even with `--icc=false`, you'd just have to emulate the rules added by Docker. You might want to give this a try, depending on how complex it is and what type of interaction with Docker itself there can be.

I remember I had an issue where Docker would remove rules that it didn't even create, just because it considered itself to be "owner" of the `DOCKER` chain; this might be fixed by now too, no idea.

**Comment by josegonzalez** [comment]
Oh I didn't even know that the private container thing had a name and docs to do it. Much nicer than my method. Thanks for pointing it out, that's _very_ much appreciated.

FWIW, I'm going to use this for the progrium/dokku project in our [official plugins](https://github.com/dokku) :)

**Comment by gdm85** [comment]
You're welcome :)

Glad to hear that :) I felt proper production firewall management of Docker containers was not (and is not?) properly covered, hence I spent some time to make this tool and publish it.

There are some areas of improvement for docker-fw, but basically it's finished in its feature set (I am particularly proud of the serialization and restore features for the firewall rules); feel free to use it there if it helps, keep me posted :)

**Comment by gdm85** [comment]
By the way, if you'd manage to emulate the rules added by Docker when publishing a port (and if it worked, of course), you'd have 0 further performance (or overall complexity) degradation (compared to tcp_fallback or even ambassador pattern), it'd be a pretty clean hack.
